name: Mirror Canva Website

on:
  push:
    branches:
      - main
  schedule:
    #- cron: '0 2 * * *' # Every day at 2 AM
    #- cron: '0 * * * *' # Every hour
    - cron: '*/30 * * * *' # Every 30 min

env:
  ORIGINAL_URL: "https://timeless-tales-workshop.my.canva.site"
  MIRROR_DOMAIN: "canva-1.naomimakkelie.nl"

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Website
        run: |
          wget --mirror --no-clobber --page-requisites --html-extension --convert-links --restrict-file-names=windows --domains "$(echo $ORIGINAL_URL | sed -E -e 's/https?:\/\/([^/]+).*/\1/')" -P ./ "$ORIGINAL_URL" || exit_code=$?
          if [ -n "$exit_code" ] && [ "$exit_code" -ne 8 ]; then
            exit $exit_code
          fi

      - name: Push to gh-pages branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          echo -n "$MIRROR_DOMAIN" > CNAME
          git add --all
          git commit -m "Mirror website"
          git push origin gh-pages --force # Use force push because gh-pages will be an orphan branch and might have different history

